<!DOCTYPE html>
<html lang="en-us">
    <head>
        <meta charset="utf-8">
        <title>Pond</title>
        <link rel="stylesheet" href="css/bootstrap.min.css">
    </head>
    <body>
        <div class="container">
            <h1>Pond</h1>
        </div><!-- /.container -->

        <script src="js/angular.min.js" charset="utf-8"></script>
        <script src="js/angular-ui-bootstrap.min.js" charset="utf-8"></script>
    </body>
</html>
